FROM ubuntu:VERSION
MAINTAINER packager@ntop.org

RUN apt-get update && \
    apt-get -y -q install wget lsb-release && \
    wget -q http://aptSTABLE.ntop.org/VERSION/all/apt-ntopSTABLE.deb && \
    dpkg -i apt-ntopSTABLE.deb && \
    rm -f apt-ntopSTABLE.deb && \
    apt-get clean all && \
    apt-get update

BACKPORTS

RUN apt-get -y install PACKAGES_LIST
RUN apt-get -y remove PACKAGES_LIST

RUN apt-get -y install PACKAGES_LIST

COPY ENTRYPOINT_PATH /tmp
ENTRYPOINT ["/tmp/ENTRYPOINT_SH"]


