FROM ubuntu:VERSION
MAINTAINER Luca Deri <deri@ntop.org>

RUN apt-get update && \
    apt-get -y -q install wget lsb-release && \
    wget -q http://aptSTABLE.ntop.org/VERSION/all/apt-ntopSTABLE.deb && \
    dpkg -i apt-ntopSTABLE.deb && \
    rm -f apt-ntopSTABLE.deb && \
    apt-get clean all && \
    apt-get update

RUN apt-get -y install PACKAGES_LIST

COPY ENTRYPOINT_PATH /tmp
ENTRYPOINT ["/tmp/ENTRYPOINT_SH"]
