FROM DISTRIBUTION:VERSION
MAINTAINER packager@ntop.org

# Fix container detection on latest docker which creates /.dockerenv too late
RUN touch /.dockerenv

RUN yum -y update && \
    yum -y -q install wget && \
    wget -q http://packages.ntop.org/centosSTABLE/ntop.repo -O ntop.repo && \
    mv ntop.repo /etc/yum.repos.d/
RUN dnf -y install dnf-plugins-core && dnf -y install epel-release && dnf config-manager --set-enabled POWERTOOLS

RUN yum -y -q erase zeromq3 ; \
    yum clean all && \
    yum -y update

# Redis is missing on some Rocky Linux versions, install it from the Remi repo
RUN dnf -y install https://rpms.remirepo.net/enterprise/remi-release-MAJORVERSION.rpm && \
    dnf -y module enable redis:remi-7.2 && \
    dnf -y install redis && \
    systemctl enable redis

RUN yum -y install PACKAGES_LIST
RUN yum -y erase PACKAGES_LIST

RUN yum -y install PACKAGES_LIST

COPY ENTRYPOINT_PATH /tmp
ENTRYPOINT ["/tmp/ENTRYPOINT_SH"]

